services:
  mongodb:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=Admin123

  mongoExpress:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=Admin123
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_SERVER=mongodb
    depends_on:
      - mongodb

  chatApp:
    image: chat_app:latest
    build:
      context: .
    ports:
      - 8080:8080
    depends_on:
      - mongodb
      - mongoExpress
    environment:
      - spring.data.mongodb.host=mongodb
      - spring.data.mongodb.username=root
      - spring.data.mongodb.password=Admin123
      - spring.data.mongodb.port=27017
      - spring.data.mongodb.authentication-database=admin
volumes:
  mongo: {}
